sudo: required
language: python
os:
    - linux
dist: xenial
services:
    - xvfb
python:
    - "3.7"
# command to install dependencies
install:
before_script:
    - pip install -U setuptools
    - pip install tox-travis
    - pip install PyQt5==5.9.2
# command to run tests
script: tox