sudo: required
language: python
os:
    - linux
dist: xenial
services:
    - xvfb
python:
    - "3.7"
# command to install dependencies
install:
before_script:
    - pip upgrade setuptools
    - pip install tox-travis
    - pip install PyQt5
# command to run tests
script: tox